### ISSUE TITLE
Rename to vulkano_window or something.

### ISSUE THREAD

**Issue by crlf0710** [PistonDevelopers/winit_window#8]
Hello this is actually a vulkano backend. This crate does not run without proper Vulkan support. Maybe this crate should be renamed, and a more general (don't be too API specific) implementation should be added.

**Comment by shinmili** [comment]
It's been a while since this issue was opened. At least this crate now "works" without vulkano, but it still has confusing APIs to me. 

The biggest part is that the constructors are feature-gated ad-hoc and initialization codes with/without vulkano look pretty different. I tried to implement `BuildFromWindowSettings` for `WinitWindow` (#16), but it works only without vulkano for now; with vulkano, a graphics API version is specified outside of piston and this doesn't fit well into `WindowSettings`.

So I'm thinking of making a `VulkanoWindow<W>`, just like [`GliumWindow<W>`](https://docs.rs/piston2d-glium_graphics/0.89.0/glium_graphics/struct.GliumWindow.html) or [~~`GfxWindow<W>`~~ `PistonWindow<W>`](https://docs.rs/piston_window/0.123.0/piston_window/struct.PistonWindow.html).

(To be honest, this "window wrapper" idea opens another question to me... Are these windows really windows? `graphics_api`, `vsync`, or `srgb`... should they be a part of `WindowSettings` in the first place?)

**Comment by shinmili** [comment]
Now I realized `VulkanoWindow` cannot be a wrapper that can take any window implementation... vulkano-win requires the backend window to be winit.
https://docs.rs/vulkano-win/latest/vulkano_win/trait.VkSurfaceBuild.html
